@startuml

namespace StealthBoardStrategy{
    namespace Front{
        namespace Client{
            class ClientBattleManger{

            }
            class ClientUnit{

            }
            class GameManger{

            }
            enum ClientGameState{

            }
        }
        namespace UI{

        }
        namespace Events{
            class ActionEventToClient{

            }
            abstract GameEventToClient{

            }
            class TurnEndEventToClient{

            }
            class TurnStartEventToClient{

            }
            GameEventToClient <|- ActionEventToClient
            GameEventToClient <|- TurnStartEventToClient
            GameEventToClient <|- TurnEndEventToClient
        }
        namespace Graphic{
            enum EffectType{

            }
        }
    }
    namespace Server{
        namespace NetworkManager{
            class NetworkManager{

            }
        }
        namespace Event{
            abstract GameEvent{
                +EventType EventType
            }
            class ActionEvent{
                +int UnitId
                +int ActionId
                +[int, int] TargetPosition
            }
            enum EventType{
                None, Action, TurnEnd, Error
            }
        }
        namespace GameLogic{
            class BattleManager{
                -int TurnProcessed
                -float RemaingTime
                -Players Turn
                -List<Character> CharacterList

                +BattleLoop()
                +PreProcess()
                +MainProcess()
                +EndProcess()
                +TurnEnd()
            }

            class BattleLogic{
                
            }

            class Board{
                -GroundTile[] tiles
            }

            class GroundTile{
                -GroundType GroundType
                -List<DotEffect> DotEffects
            }

            enum Players{
                Player1, Player2
            }
        }
        namespace DataBase{
            class Unit{
                -[int, bool] Id
                -[string, bool] Name
                + Players LocatedSide
                -[int, bool] Position
                -[int, int, bool] Hp
                -[int, int, bool] Regen
                -[int, int, bool] Mana
                -[int, int, bool] ManaRegen
                -[int, int, bool] Stealthiness
                -[int, int, bool] MaxStealthiness
                -[int, int, bool] Atk
                -[int, int, bool] Mp
                -[int, int, bool] Def
                -[int, int, bool] MR
                -[int, int, bool] Speed
                -[int, int, bool] Calculation
                -int ActionPoint
                -Buff[] buffs
                +RevealStatus()
                +AddBuff()
                +DeleteBuff()
                +ProcessBuff()
                +Damage()
                +TrueDamage()
                +Move()
                -bool IsActive
            }
            class Hunter{

            }

            class Demon{

            }

            class Rune{

            }

            class Building{

            }
            class Skill{
                -(int, bool) Id
                -(string, bool) Name
                -SkillType SkillType
                -List<int> args

            }

            class Buff{
                -(int, bool) Id
                -(string, bool) Name
            }

            class DotEffect{
                -DotEffectType DotEffectType
                -int Duration
                -int CurrentTime
                -int Power
            }

            enum DotEffectType{
                None, Fire
            }

            enum GroundType{
                None, Normal, Glassy, Swamp, Rocky
            }

            enum UnitType{
                Hunter, Demon, Rune, Building
            }

            enum SkillType{

            }
            enum BuffType{

            }
        }
    }
}

@enduml